# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 01c13947f0c20f9f1da585b94e387550b397d4a9b2f020a3c9bfcb214eff42c8edcc51803bd41f295922a6c9529a6d0f0b0e4d3f80893d466e21d3301f6a2f59

test:
  secret_key_base: bf4bd5fba4c169c51ffd812d67208bd443c57f37e04c184fe95366585f1e5f23294b7c7b6a9d233ee1eb1287fad8a13e172b85822750bc44af11a1418cc56fc4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
